language: node_js
node_js:
  - '10'
script:
  - npm run lint
  - npm test
  - npm run build
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_deploy:
  - touch .npmignore
deploy:
  provider: npm
  email: 'collis.michael@gmail.com'
  access: public
  skip_cleanup: true
  edge: true
  on:
    tags: true
