language: node_js
node_js:
  - '10'
script:
  - npm run lint
  - npm test
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_deploy: 'rm -rf .gitignore'
deploy:
  provider: npm
  on:
    tags: true
