language: node_js
node_js:
  - '10'

script:
  - npm run lint
  - npm test
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_deploy:
  - echo > .npmignore
  - npm run build
deploy:
  provider: npm
  email: collis.michael@gmail.com
  api_key: $NPM_API_TOKEN
  skip_cleanup: true
  on:
    tags: true
