language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '5'
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
